
[env]
  TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
size = 12

[window]
opacity = 0.8

[general]
# Catpuccin Color Scheme
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

#[shell]
#program = "~/.config/alacritty/tmux-chooser.sh"
#args = "-AsDev"
